[atcoder]
submit_via_binary = false # submit via binary by default
use_cross = false         # use `cross` instead of `cargo` when generating binaries
binary_column = 80        # maximum column number of generated binary (0 for no wrapping)
update_interval = 1000    # interval time of fetching result (ms)
strip_path = "strip"      # specify `strip` command path. NOTE: if you use macOS, you have to install GNU strip and specify its path here.

[profile]
# target to use to generate binary
target = "x86_64-unknown-linux-musl"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
ac-library-rs = "0.1.1"
# num = "0.2.1"
# rand = { version = "0.7.3", features = ["small_rng"] }
regex = "1.3.6"
# ascii = "1.0.0"
itertools = "0.9.0"
proconio = { version = "0.3.6", features = ["derive"] }

[project]
# to create `rust-toolchain` file, uncomment this line.
# rustc_version = "1.15.1"

# source code template
template = """
#![allow(unused_imports)]
use proconio::*;
use proconio::marker::*;

fn main() {
    input! {

    }
}

"""
